server:
  port: 8181
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/UserService-MS
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
   
   #to resiter in eureca server
  application:
    name: USER_SERVICE
eureka:
  instance:
    ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
      
      
      
      
        