server:
  port: 8383
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RatingService-MS
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#config to add in eureca server
  application:
    name: RATING-SERVICE
eureka:
  instance:
    ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/   
      
         